# Pattern-based word generation.
#
# Pattern tokens:
#   ?w   one of the loaded input words
#   ?d   digit 0-9
#   ?l   lowercase letter a-z
#   ?u   uppercase letter A-Z
#   ?s   special character  ! @ # $ % ^ & * ( ) - _ + =
#   ?a   alpha (a-z + A-Z)
#   ?n   alphanumeric (a-z + A-Z + 0-9)
#   ?x   any printable (alpha + digit + special)
#   ??   literal '?'
#   <c>  any other character is treated as a literal
#
# Example: "?w?d?d?d?d" generates each input word followed by every
# four-digit combination (10 000 per word).
module Worcestershire
  class PatternGenerator
    DIGITS   = ('0'..'9').to_a.map(&.to_s)
    LOWER    = ('a'..'z').to_a.map(&.to_s)
    UPPER    = ('A'..'Z').to_a.map(&.to_s)
    SPECIAL  = "!@#$%^&*()-_+=".chars.map(&.to_s)
    ALPHA    = LOWER + UPPER
    ALPHANUM = ALPHA + DIGITS
    ANY      = ALPHANUM + SPECIAL

    @words : Array(String)
    @max : UInt64?
    @count : UInt64

    def initialize(@words : Array(String), max : UInt64? = nil)
      @max = max
      @count = 0_u64
    end

    # Yield each string generated by the pattern.
    # Stops early when the internal max-combinations limit is reached.
    def generate(pattern : String, &block : String ->)
      tokens = tokenize(pattern)
      @count = 0_u64
      expand(tokens, 0, "", &block)
    end

    private def tokenize(pattern : String) : Array(Array(String))
      tokens = [] of Array(String)
      i = 0
      while i < pattern.size
        if pattern[i] == '?' && i + 1 < pattern.size
          set = case pattern[i + 1]
                when 'w' then @words
                when 'd' then DIGITS
                when 'l' then LOWER
                when 'u' then UPPER
                when 's' then SPECIAL
                when 'a' then ALPHA
                when 'n' then ALPHANUM
                when 'x' then ANY
                when '?' then ["?"]
                else          ["?#{pattern[i + 1]}"]
                end
          tokens << set
          i += 2
        else
          tokens << [pattern[i].to_s]
          i += 1
        end
      end
      tokens
    end

    private def expand(tokens : Array(Array(String)),
                       idx : Int32,
                       current : String,
                       &block : String ->)
      if (lim = @max) && @count >= lim
        return
      end

      if idx == tokens.size
        block.call(current)
        @count += 1
        return
      end

      tokens[idx].each do |part|
        break if (lim = @max) && @count >= lim
        expand(tokens, idx + 1, current + part, &block)
      end
    end
  end
end
